### ISSUE TITLE
Add CircleCI to repository

### ISSUE THREAD

**Issue by lukebaker** [bstewart/princeton_methods_camp#11]
@bstewart, I added some CircleCI setup to the repository to ensure that the site builds with every commit. However, as the repository owner, I'll need you to actually enable / install CircleCI for this repository. CircleCI will run these builds for free for public repositories, so there's no need for more than their free plan.

Here are the steps:

1. Visit the [CircleCI signup page](https://circleci.com/signup/)
2. Next to the "Sign up with GitHub" button click the down arrow and then "Public Repos Only" [[screenshot]](https://user-images.githubusercontent.com/84748/57531829-5d137680-7308-11e9-8aa0-f0f6b9f0bf1f.png)
3. Click "Authorize circleci" [[screenshot]](https://user-images.githubusercontent.com/84748/57531902-90ee9c00-7308-11e9-8cbe-a61b90d120a2.png)
4. From the [CircleCI dashboard](https://circleci.com/dashboard), click "Add Projects".
5. Find "princeton_methods_camp" and click "Set Up Project"
6. Click "Start Building"

I think that's all. Let me know if you have any questions. Thanks!

/cc @msalganik

**Comment by bstewart** [comment]
no problem. should be set but let me know if it isn't working.

**Comment by lukebaker** [comment]
Looks great. Thanks, @bstewart.
![Screenshot from 2019-05-10 12-03-52](https://user-images.githubusercontent.com/84748/57540878-bc2eb680-731b-11e9-8e31-eb32de49b7d1.png)
