### ISSUE TITLE
Update DNS configuration for pusocmethodscamp.org

### ISSUE THREAD

**Issue by lukebaker** [bstewart/princeton_methods_camp#9]
In order to support HTTPS, we need to update the DNS configuration for pusocmethodscamp.org. Currently it is configured with two IP addresses starting with `192.30.252.x`. Those IPs are older ones and should be updated.

The [documentation says](https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider) it should have A records pointing at:
* 185.199.108.153
* 185.199.109.153
* 185.199.110.153
* 185.199.111.153

*Note*: the configuration for www.pusocmethodscamp.org does **NOT** need to be altered.

Once this is set and we've given the DNS records time to propagate, we can move to the next step in enabling HTTPS.

**Comment by msalganik** [comment]
Thanks @lukebaker.  @bstewart can you make the change that Luke described above?  No rush.

**Comment by bstewart** [comment]
@lukebaker okay I think I made this change correctly but let me know if I didn't.

**Comment by lukebaker** [comment]
@bstewart looks good from here! To finish enabling HTTPS you can select the "Enforce HTTPS" checkbox here: https://github.com/bstewart/princeton_methods_camp/settings

**Comment by bstewart** [comment]
@lukebaker It is already checked and grayed out.  see image.
![image](https://user-images.githubusercontent.com/577337/56393959-dafdc980-6203-11e9-93c4-6674e78c4321.png)

**Comment by lukebaker** [comment]
It looks like we first need to address the warning at the top of that screenshot:

> The CNAME pusocmethodscamp.org is already taken.

I think this means that your repository is not actually publishing to that domain. From the [linked documentation](https://help.github.com/en/articles/troubleshooting-custom-domains#cname-already-taken):

> If you don't own the repository that contains the CNAME file with your custom domain, try to contact the owner and ask them to update their custom domain. If you're unsure which repository contains the CNAME file with your custom domain, contact [GitHub Support](https://github.com/contact).

I think the fork that @xyd created is actually publishing to that domain. I believe the way to fix that is to get @xyd to alter the settings on her fork to not use pusocmethodscamp.org (or simply remove the fork if she's done with it).

**Comment by msalganik** [comment]
With @xyd permission I have deleted her branch.  

@lukebaker does that resolve the problem?

**Comment by lukebaker** [comment]
> @lukebaker does that resolve the problem?

I think so, but we'll need @bstewart to confirm what the [settings page](https://github.com/bstewart/princeton_methods_camp/settings) shows. We want:
1. To not see a warning about the CNAME already being taken.
2. Source set to `master`.
3. Custom domain set to pusocmethodscamp.org.
4. Enforce HTTPS checked.

**Comment by bstewart** [comment]
This appears to be all set.

**Comment by bstewart** [comment]
when I type in the custom domain it says at the top that it has made no changes to the custom domain but presumably that's because it is already set?

**Comment by bstewart** [comment]
Of course, it also doesn't appear to be working.  I'll await instructions from @lukebaker

**Comment by lukebaker** [comment]
Thanks, @bstewart. It looks like things are working now after I pushed a minor update to the `master` branch. I've confirmed that the `master` branch does deploy to our domain. It doesn't look like HTTPS is working, but the documentation suggests it may take up to an hour for that to start working. That hour might have started after my minor update from about ~10 minutes ago.

**Comment by lukebaker** [comment]
Looks like HTTPS is working for me, now. https://pusocmethodscamp.org/

Thanks @bstewart, @msalganik, and @xyd for helping get all this sorted out. I'll close this issue now.

**Comment by msalganik** [comment]
Agreed.  And thank you @lukebaker.
